nohup python -u run.py --train --algo MCST --draw_path ./log/1 --gpu 0 --epochs 30 --search_time 1000 --max_a_len 10 --beta 100 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_100_30_1000_10.txt 2>&1 &
nohup python -u run.py --train --algo MCST --draw_path ./log/2 --gpu 1 --epochs 30 --search_time 1000 --max_a_len 10 --beta 10 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_10_30_1000_10.txt 2>&1 &
nohup python -u run.py --train --algo MCST --draw_path ./log/3 --gpu 2 --epochs 30 --search_time 1000 --max_a_len 10 --beta 1 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_1_30_1000_10.txt 2>&1 &
nohup python -u run.py --train --algo MCST --draw_path ./log/4 --gpu 3 --epochs 30 --search_time 1000 --max_a_len 10 --beta 0.1 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_0.1_30_1000_10.txt 2>&1 &

nohup python -u run.py --train --algo MCST --draw_path ./log/5 --gpu 0 --epochs 30 --search_time 3000 --max_a_len 10 --beta 100 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_100_30_3000_10.txt 2>&1 &
nohup python -u run.py --train --algo MCST --draw_path ./log/6 --gpu 1 --epochs 30 --search_time 3000 --max_a_len 10 --beta 10 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_10_30_3000_10.txt 2>&1 &
nohup python -u run.py --train --algo MCST --draw_path ./log/7 --gpu 2 --epochs 30 --search_time 3000 --max_a_len 10 --beta 1 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_1_30_3000_10.txt 2>&1 &
nohup python -u run.py --train --algo MCST --draw_path ./log/8 --gpu 3 --epochs 30 --search_time 3000 --max_a_len 10 --beta 0.1 --batch_size 1 --max_p_len 10000 --hidden_size 150  --train_files ../data/demo/trainset/search.train.json --dev_files  ../data/demo/devset/search.dev.json --test_files ../data/demo/test/search.test.json ../data/demo/test/search.test.json >beta_0.1_30_3000_10.txt 2>&1 &

